/**
 * npm run seed
 *
 * Source: data/player-country-team-dataset.csv
 *   Columns: player, ipl_team, country
 *   One row per player-franchise stint. A player with multiple IPL teams
 *   appears on multiple rows — these are aggregated into a single entry.
 *
 * Outputs → src/data/players.ts
 */

import fs from 'fs/promises';
import path from 'path';

interface CricketPlayer {
  id: string;
  name: string;
  aliases: string[];
  teams: string[];
  testRuns: number;
  testWickets: number;
  odiWickets: number;
  t20iWickets: number;
  testCenturies: number;
  worldCupWins: string[];
  iplTeams: string[];
  captainedNational: boolean;
  isAllrounder: boolean;
}

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

async function main() {
  console.log('\n🏏  Hit Miss Out — Player Data Seeder\n');

  // 1. Read and parse CSV ────────────────────────────────────────────────────
  const csvPath = path.join(process.cwd(), 'data/player-country-team-dataset.csv');
  const raw = await fs.readFile(csvPath, 'utf-8');
  const lines = raw.trim().split('\n').slice(1); // skip header row

  console.log(`Parsed ${lines.length} rows from CSV…`);

  // 2. Aggregate by player name ──────────────────────────────────────────────
  // A player may appear multiple times with different IPL teams.
  // Use the last seen country (always consistent per player in this dataset).
  const playerMap = new Map<string, { iplTeams: Set<string>; country: string }>();

  for (const line of lines) {
    const commaIdx1 = line.indexOf(',');
    const commaIdx2 = line.indexOf(',', commaIdx1 + 1);
    if (commaIdx1 === -1 || commaIdx2 === -1) continue;

    const name    = line.slice(0, commaIdx1).trim();
    const iplTeam = line.slice(commaIdx1 + 1, commaIdx2).trim();
    const country = line.slice(commaIdx2 + 1).trim();

    if (!name || !country) continue;

    if (!playerMap.has(name)) {
      playerMap.set(name, { iplTeams: new Set(), country });
    }
    if (iplTeam) {
      playerMap.get(name)!.iplTeams.add(iplTeam);
    }
  }

  console.log(`  → ${playerMap.size} unique players\n`);

  // 3. Build CricketPlayer[] ────────────────────────────────────────────────
  const players: CricketPlayer[] = [];

  for (const [name, { iplTeams, country }] of playerMap) {
    players.push({
      id:               slugify(name),
      name,
      aliases:          [],
      teams:            [country],
      testRuns:         0,
      testWickets:      0,
      odiWickets:       0,
      t20iWickets:      0,
      testCenturies:    0,
      worldCupWins:     [],
      iplTeams:         [...iplTeams].sort(),
      captainedNational: false,
      isAllrounder:     false,
    });
  }

  // Sort alphabetically by name
  players.sort((a, b) => a.name.localeCompare(b.name));

  // 4. Write output ─────────────────────────────────────────────────────────
  const ts = [
    `import type { CricketPlayer } from '../types';`,
    ``,
    `// Auto-generated by \`npm run seed\` on ${new Date().toISOString()}`,
    `// Source: data/player-country-team-dataset.csv`,
    ``,
    `export const PLAYERS: CricketPlayer[] = ${JSON.stringify(players, null, 2)};`,
  ].join('\n');

  const outFile = path.join(process.cwd(), 'src/data/players.ts');
  await fs.writeFile(outFile, ts);

  console.log(`✅  Done — ${players.length} players written to src/data/players.ts\n`);

  // Summary by country
  const byCountry: Record<string, number> = {};
  for (const p of players) {
    const c = p.teams[0];
    byCountry[c] = (byCountry[c] ?? 0) + 1;
  }
  console.log('  Players per country:');
  for (const [c, n] of Object.entries(byCountry).sort((a, b) => b[1] - a[1]))
    console.log(`    ${c.padEnd(16)} ${n}`);

  // Summary by IPL team
  const byIpl: Record<string, number> = {};
  for (const p of players) {
    for (const t of p.iplTeams) {
      byIpl[t] = (byIpl[t] ?? 0) + 1;
    }
  }
  console.log('\n  Players per IPL team:');
  for (const [t, n] of Object.entries(byIpl).sort((a, b) => b[1] - a[1]))
    console.log(`    ${t.padEnd(30)} ${n}`);
  console.log();
}

main().catch(err => { console.error('\n❌  Seeder failed:', err); process.exit(1); });
