import type { CricketPlayer } from '../types';

// Auto-generated by `npm run seed` on 2026-05-07T09:58:23.329Z
// Stats baseline: src/data/players.ts (edit manually then re-run seed)
// Metadata (IPL teams, roles): Wikidata SPARQL
// World Cup winners: scripts/lib/worldcup.ts

export const PLAYERS: CricketPlayer[] = [
  {
    "id": "muttiah-muralitharan",
    "name": "Muttiah Muralitharan",
    "aliases": [
      "muralitharan",
      "murali",
      "muttiah"
    ],
    "teams": [
      "Sri Lanka"
    ],
    "testRuns": 1261,
    "testWickets": 800,
    "odiWickets": 534,
    "t20iWickets": 13,
    "testCenturies": 0,
    "worldCupWins": [
      "1996"
    ],
    "iplTeams": [
      "Royal Challengers Bangalore",
      "Kochi Tuskers Kerala"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "shane-warne",
    "name": "Shane Warne",
    "aliases": [
      "warne",
      "warnie",
      "king of spin"
    ],
    "teams": [
      "Australia"
    ],
    "testRuns": 3154,
    "testWickets": 708,
    "odiWickets": 293,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [
      "1999",
      "2003"
    ],
    "iplTeams": [
      "Rajasthan Royals"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "james-anderson-8608",
    "name": "James Anderson",
    "aliases": [
      "anderson",
      "jimmy"
    ],
    "teams": [
      "England"
    ],
    "testRuns": 1352,
    "testWickets": 704,
    "odiWickets": 269,
    "t20iWickets": 18,
    "testCenturies": 0,
    "worldCupWins": [
      "1999",
      "2003",
      "2007"
    ],
    "iplTeams": [],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "jacques-kallis-45789",
    "name": "Jacques Kallis",
    "aliases": [
      "kallis",
      "jk"
    ],
    "teams": [
      "South Africa"
    ],
    "testRuns": 13289,
    "testWickets": 292,
    "odiWickets": 273,
    "t20iWickets": 2,
    "testCenturies": 45,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru",
      "Kolkata Knight Riders"
    ],
    "captainedNational": false,
    "isAllrounder": true
  },
  {
    "id": "stuart-broad",
    "name": "Stuart Broad",
    "aliases": [
      "broad",
      "broady"
    ],
    "teams": [
      "England"
    ],
    "testRuns": 3265,
    "testWickets": 604,
    "odiWickets": 178,
    "t20iWickets": 65,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "anil-kumble",
    "name": "Anil Kumble",
    "aliases": [
      "kumble",
      "jumbo"
    ],
    "teams": [
      "India"
    ],
    "testRuns": 2506,
    "testWickets": 619,
    "odiWickets": 337,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bangalore"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "r-ashwin",
    "name": "R Ashwin",
    "aliases": [
      "ashwin",
      "ravichandran ashwin",
      "ash"
    ],
    "teams": [
      "India"
    ],
    "testRuns": 3200,
    "testWickets": 537,
    "odiWickets": 156,
    "t20iWickets": 72,
    "testCenturies": 6,
    "worldCupWins": [],
    "iplTeams": [
      "Chennai Super Kings",
      "Kings XI Punjab",
      "Rajasthan Royals",
      "Delhi Capitals"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "kapil-dev",
    "name": "Kapil Dev",
    "aliases": [
      "kapil",
      "haryana hurricane"
    ],
    "teams": [
      "India"
    ],
    "testRuns": 5248,
    "testWickets": 434,
    "odiWickets": 253,
    "t20iWickets": 0,
    "testCenturies": 8,
    "worldCupWins": [
      "1983"
    ],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": true
  },
  {
    "id": "glenn-mcgrath",
    "name": "Glenn McGrath",
    "aliases": [
      "mcgrath",
      "pigeon"
    ],
    "teams": [
      "Australia"
    ],
    "testRuns": 641,
    "testWickets": 563,
    "odiWickets": 381,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [
      "1999",
      "2003",
      "2007"
    ],
    "iplTeams": [],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "sachin-tendulkar-35320",
    "name": "Sachin Tendulkar",
    "aliases": [
      "sachin",
      "tendulkar",
      "the little master",
      "master blaster"
    ],
    "teams": [
      "India"
    ],
    "testRuns": 15921,
    "testWickets": 46,
    "odiWickets": 154,
    "t20iWickets": 0,
    "testCenturies": 51,
    "worldCupWins": [
      "2011"
    ],
    "iplTeams": [
      "Mumbai Indians"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "ian-botham",
    "name": "Ian Botham",
    "aliases": [
      "botham",
      "beefy",
      "both"
    ],
    "teams": [
      "England"
    ],
    "testRuns": 5200,
    "testWickets": 383,
    "odiWickets": 145,
    "t20iWickets": 0,
    "testCenturies": 14,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": true
  },
  {
    "id": "courtney-walsh-53216",
    "name": "Courtney Walsh",
    "aliases": [
      "walsh"
    ],
    "teams": [
      "West Indies"
    ],
    "testRuns": 936,
    "testWickets": 519,
    "odiWickets": 227,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "shaun-pollock",
    "name": "Shaun Pollock",
    "aliases": [
      "pollock",
      "shaun"
    ],
    "teams": [
      "South Africa"
    ],
    "testRuns": 3781,
    "testWickets": 421,
    "odiWickets": 393,
    "t20iWickets": 0,
    "testCenturies": 2,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": true
  },
  {
    "id": "richard-hadlee-37224",
    "name": "Richard Hadlee",
    "aliases": [
      "hadlee",
      "sir richard",
      "paddles"
    ],
    "teams": [
      "New Zealand"
    ],
    "testRuns": 3124,
    "testWickets": 431,
    "odiWickets": 158,
    "t20iWickets": 0,
    "testCenturies": 2,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": false,
    "isAllrounder": true
  },
  {
    "id": "daniel-vettori",
    "name": "Daniel Vettori",
    "aliases": [
      "vettori",
      "dan"
    ],
    "teams": [
      "New Zealand"
    ],
    "testRuns": 4531,
    "testWickets": 362,
    "odiWickets": 305,
    "t20iWickets": 73,
    "testCenturies": 6,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bangalore"
    ],
    "captainedNational": true,
    "isAllrounder": true
  },
  {
    "id": "wasim-akram",
    "name": "Wasim Akram",
    "aliases": [
      "wasim",
      "sultan of swing"
    ],
    "teams": [
      "Pakistan"
    ],
    "testRuns": 2898,
    "testWickets": 414,
    "odiWickets": 502,
    "t20iWickets": 0,
    "testCenturies": 3,
    "worldCupWins": [
      "1992"
    ],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "garfield-sobers-52946",
    "name": "Garfield Sobers",
    "aliases": [
      "sobers",
      "gary sobers",
      "garfield",
      "sir garfield"
    ],
    "teams": [
      "West Indies"
    ],
    "testRuns": 8032,
    "testWickets": 235,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 26,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": true
  },
  {
    "id": "dale-steyn-47492",
    "name": "Dale Steyn",
    "aliases": [
      "steyn",
      "dale"
    ],
    "teams": [
      "South Africa"
    ],
    "testRuns": 1663,
    "testWickets": 439,
    "odiWickets": 196,
    "t20iWickets": 64,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "joe-root",
    "name": "Joe Root",
    "aliases": [
      "root",
      "rooty"
    ],
    "teams": [
      "England"
    ],
    "testRuns": 12972,
    "testWickets": 62,
    "odiWickets": 27,
    "t20iWickets": 5,
    "testCenturies": 35,
    "worldCupWins": [
      "2019"
    ],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "imran-khan-40614",
    "name": "Imran Khan",
    "aliases": [
      "imran",
      "lion of lahore"
    ],
    "teams": [
      "Pakistan"
    ],
    "testRuns": 3807,
    "testWickets": 362,
    "odiWickets": 182,
    "t20iWickets": 0,
    "testCenturies": 6,
    "worldCupWins": [
      "1992"
    ],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": true
  },
  {
    "id": "steve-waugh",
    "name": "Steve Waugh",
    "aliases": [
      "steve waugh",
      "tugga",
      "iceman"
    ],
    "teams": [
      "Australia"
    ],
    "testRuns": 10927,
    "testWickets": 92,
    "odiWickets": 195,
    "t20iWickets": 0,
    "testCenturies": 32,
    "worldCupWins": [
      "1987",
      "1999"
    ],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "curtly-ambrose-51107",
    "name": "Curtly Ambrose",
    "aliases": [
      "ambrose",
      "curtly"
    ],
    "teams": [
      "West Indies"
    ],
    "testRuns": 1439,
    "testWickets": 405,
    "odiWickets": 225,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "ricky-ponting",
    "name": "Ricky Ponting",
    "aliases": [
      "ponting",
      "punter"
    ],
    "teams": [
      "Australia"
    ],
    "testRuns": 13378,
    "testWickets": 5,
    "odiWickets": 3,
    "t20iWickets": 0,
    "testCenturies": 41,
    "worldCupWins": [
      "1999",
      "2003",
      "2007"
    ],
    "iplTeams": [
      "Mumbai Indians"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "rahul-dravid",
    "name": "Rahul Dravid",
    "aliases": [
      "dravid",
      "the wall",
      "jammy"
    ],
    "teams": [
      "India"
    ],
    "testRuns": 13288,
    "testWickets": 1,
    "odiWickets": 4,
    "t20iWickets": 0,
    "testCenturies": 36,
    "worldCupWins": [],
    "iplTeams": [
      "Rajasthan Royals"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "malcolm-marshall-52419",
    "name": "Malcolm Marshall",
    "aliases": [
      "marshall",
      "maco"
    ],
    "teams": [
      "West Indies"
    ],
    "testRuns": 1810,
    "testWickets": 376,
    "odiWickets": 157,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "ravindra-jadeja",
    "name": "Ravindra Jadeja",
    "aliases": [
      "jadeja",
      "jaddu",
      "sir jadeja",
      "rockstar"
    ],
    "teams": [
      "India"
    ],
    "testRuns": 3350,
    "testWickets": 312,
    "odiWickets": 194,
    "t20iWickets": 54,
    "testCenturies": 3,
    "worldCupWins": [],
    "iplTeams": [
      "Chennai Super Kings",
      "Gujarat Lions",
      "Rajasthan Royals"
    ],
    "captainedNational": false,
    "isAllrounder": true
  },
  {
    "id": "chaminda-vaas",
    "name": "Chaminda Vaas",
    "aliases": [
      "vaas",
      "chaminda"
    ],
    "teams": [
      "Sri Lanka"
    ],
    "testRuns": 2025,
    "testWickets": 355,
    "odiWickets": 400,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [
      "1996"
    ],
    "iplTeams": [],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "alastair-cook",
    "name": "Alastair Cook",
    "aliases": [
      "cook",
      "the chef"
    ],
    "teams": [
      "England"
    ],
    "testRuns": 12472,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 33,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "ben-stokes",
    "name": "Ben Stokes",
    "aliases": [
      "stokes",
      "baz"
    ],
    "teams": [
      "England"
    ],
    "testRuns": 6469,
    "testWickets": 200,
    "odiWickets": 74,
    "t20iWickets": 28,
    "testCenturies": 13,
    "worldCupWins": [
      "2019"
    ],
    "iplTeams": [
      "Rising Pune Supergiants",
      "Rajasthan Royals"
    ],
    "captainedNational": true,
    "isAllrounder": true
  },
  {
    "id": "kumar-sangakkara",
    "name": "Kumar Sangakkara",
    "aliases": [
      "sangakkara",
      "sanga"
    ],
    "teams": [
      "Sri Lanka"
    ],
    "testRuns": 12400,
    "testWickets": 0,
    "odiWickets": 1,
    "t20iWickets": 0,
    "testCenturies": 38,
    "worldCupWins": [],
    "iplTeams": [
      "Deccan Chargers",
      "Kings XI Punjab"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "allan-border",
    "name": "Allan Border",
    "aliases": [
      "border",
      "ab"
    ],
    "teams": [
      "Australia"
    ],
    "testRuns": 11174,
    "testWickets": 39,
    "odiWickets": 73,
    "t20iWickets": 0,
    "testCenturies": 27,
    "worldCupWins": [
      "1987"
    ],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "makhaya-ntini",
    "name": "Makhaya Ntini",
    "aliases": [
      "ntini",
      "makhaya"
    ],
    "teams": [
      "South Africa"
    ],
    "testRuns": 601,
    "testWickets": 390,
    "odiWickets": 266,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "waqar-younis",
    "name": "Waqar Younis",
    "aliases": [
      "waqar"
    ],
    "teams": [
      "Pakistan"
    ],
    "testRuns": 1010,
    "testWickets": 373,
    "odiWickets": 416,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [
      "1992"
    ],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "brian-lara",
    "name": "Brian Lara",
    "aliases": [
      "lara",
      "prince of trinidad"
    ],
    "teams": [
      "West Indies"
    ],
    "testRuns": 11953,
    "testWickets": 0,
    "odiWickets": 4,
    "t20iWickets": 0,
    "testCenturies": 34,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "shivnarine-chanderpaul-51469",
    "name": "Shivnarine Chanderpaul",
    "aliases": [
      "chanderpaul",
      "shiv"
    ],
    "teams": [
      "West Indies"
    ],
    "testRuns": 11867,
    "testWickets": 0,
    "odiWickets": 7,
    "t20iWickets": 0,
    "testCenturies": 30,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "mahela-jayawardene",
    "name": "Mahela Jayawardene",
    "aliases": [
      "jayawardene",
      "mahela"
    ],
    "teams": [
      "Sri Lanka"
    ],
    "testRuns": 11814,
    "testWickets": 1,
    "odiWickets": 5,
    "t20iWickets": 0,
    "testCenturies": 34,
    "worldCupWins": [],
    "iplTeams": [
      "Kochi Tuskers Kerala",
      "Delhi Capitals"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "mitchell-starc",
    "name": "Mitchell Starc",
    "aliases": [
      "starc",
      "mitch"
    ],
    "teams": [
      "Australia"
    ],
    "testRuns": 740,
    "testWickets": 342,
    "odiWickets": 241,
    "t20iWickets": 66,
    "testCenturies": 0,
    "worldCupWins": [
      "2015",
      "2023"
    ],
    "iplTeams": [
      "Kolkata Knight Riders"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "andrew-flintoff",
    "name": "Andrew Flintoff",
    "aliases": [
      "flintoff",
      "freddie"
    ],
    "teams": [
      "England"
    ],
    "testRuns": 3845,
    "testWickets": 226,
    "odiWickets": 169,
    "t20iWickets": 10,
    "testCenturies": 5,
    "worldCupWins": [],
    "iplTeams": [
      "Chennai Super Kings"
    ],
    "captainedNational": true,
    "isAllrounder": true
  },
  {
    "id": "allan-donald-44716",
    "name": "Allan Donald",
    "aliases": [
      "donald",
      "white lightning"
    ],
    "teams": [
      "South Africa"
    ],
    "testRuns": 652,
    "testWickets": 330,
    "odiWickets": 272,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "trent-boult",
    "name": "Trent Boult",
    "aliases": [
      "boult",
      "trent"
    ],
    "teams": [
      "New Zealand"
    ],
    "testRuns": 1040,
    "testWickets": 317,
    "odiWickets": 169,
    "t20iWickets": 62,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Mumbai Indians",
      "Rajasthan Royals"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "younis-khan",
    "name": "Younis Khan",
    "aliases": [
      "younis",
      "younus"
    ],
    "teams": [
      "Pakistan"
    ],
    "testRuns": 10099,
    "testWickets": 4,
    "odiWickets": 4,
    "t20iWickets": 0,
    "testCenturies": 34,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "kane-williamson",
    "name": "Kane Williamson",
    "aliases": [
      "williamson",
      "kane"
    ],
    "teams": [
      "New Zealand"
    ],
    "testRuns": 9049,
    "testWickets": 37,
    "odiWickets": 39,
    "t20iWickets": 16,
    "testCenturies": 33,
    "worldCupWins": [],
    "iplTeams": [
      "Sunrisers Hyderabad",
      "Gujarat Titans"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "sunil-gavaskar",
    "name": "Sunil Gavaskar",
    "aliases": [
      "gavaskar",
      "sunny",
      "little master"
    ],
    "teams": [
      "India"
    ],
    "testRuns": 10122,
    "testWickets": 1,
    "odiWickets": 1,
    "t20iWickets": 0,
    "testCenturies": 34,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "angelo-mathews-49764",
    "name": "Angelo Mathews",
    "aliases": [
      "mathews",
      "angelo"
    ],
    "teams": [
      "Sri Lanka"
    ],
    "testRuns": 7507,
    "testWickets": 83,
    "odiWickets": 110,
    "t20iWickets": 32,
    "testCenturies": 12,
    "worldCupWins": [
      "1996"
    ],
    "iplTeams": [
      "Delhi Capitals",
      "Kolkata Knight Riders"
    ],
    "captainedNational": true,
    "isAllrounder": true
  },
  {
    "id": "sanath-jayasuriya",
    "name": "Sanath Jayasuriya",
    "aliases": [
      "jayasuriya",
      "sanath",
      "matara mauler"
    ],
    "teams": [
      "Sri Lanka"
    ],
    "testRuns": 6973,
    "testWickets": 98,
    "odiWickets": 323,
    "t20iWickets": 0,
    "testCenturies": 14,
    "worldCupWins": [
      "1996"
    ],
    "iplTeams": [
      "Mumbai Indians"
    ],
    "captainedNational": true,
    "isAllrounder": true
  },
  {
    "id": "chris-cairns-36597",
    "name": "Chris Cairns",
    "aliases": [
      "cairns",
      "chris cairns"
    ],
    "teams": [
      "New Zealand"
    ],
    "testRuns": 3320,
    "testWickets": 218,
    "odiWickets": 201,
    "t20iWickets": 0,
    "testCenturies": 5,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": false,
    "isAllrounder": true
  },
  {
    "id": "virender-sehwag",
    "name": "Virender Sehwag",
    "aliases": [
      "sehwag",
      "viru",
      "nawab of najafgarh"
    ],
    "teams": [
      "India"
    ],
    "testRuns": 8586,
    "testWickets": 40,
    "odiWickets": 96,
    "t20iWickets": 1,
    "testCenturies": 23,
    "worldCupWins": [
      "2011"
    ],
    "iplTeams": [
      "Delhi Capitals",
      "Kings XI Punjab"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "graeme-smith-47270",
    "name": "Graeme Smith",
    "aliases": [
      "graeme smith",
      "biff"
    ],
    "teams": [
      "South Africa"
    ],
    "testRuns": 9265,
    "testWickets": 17,
    "odiWickets": 35,
    "t20iWickets": 1,
    "testCenturies": 27,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "steve-smith",
    "name": "Steve Smith",
    "aliases": [
      "steve smith",
      "smudge",
      "smithy"
    ],
    "teams": [
      "Australia"
    ],
    "testRuns": 9207,
    "testWickets": 18,
    "odiWickets": 32,
    "t20iWickets": 3,
    "testCenturies": 32,
    "worldCupWins": [
      "2015",
      "2023"
    ],
    "iplTeams": [
      "Rajasthan Royals",
      "Pune Supergiants"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "viv-richards",
    "name": "Viv Richards",
    "aliases": [
      "viv",
      "sir viv",
      "master blaster",
      "vivian richards"
    ],
    "teams": [
      "West Indies"
    ],
    "testRuns": 8540,
    "testWickets": 32,
    "odiWickets": 118,
    "t20iWickets": 0,
    "testCenturies": 24,
    "worldCupWins": [
      "1975",
      "1979"
    ],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "javed-miandad",
    "name": "Javed Miandad",
    "aliases": [
      "miandad",
      "javed"
    ],
    "teams": [
      "Pakistan"
    ],
    "testRuns": 8832,
    "testWickets": 17,
    "odiWickets": 7,
    "t20iWickets": 0,
    "testCenturies": 23,
    "worldCupWins": [
      "1992"
    ],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "hashim-amla-43906",
    "name": "Hashim Amla",
    "aliases": [
      "amla",
      "hash"
    ],
    "teams": [
      "South Africa"
    ],
    "testRuns": 9282,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 28,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "virat-kohli",
    "name": "Virat Kohli",
    "aliases": [
      "kohli",
      "virat",
      "king kohli",
      "king"
    ],
    "teams": [
      "India"
    ],
    "testRuns": 9230,
    "testWickets": 0,
    "odiWickets": 4,
    "t20iWickets": 0,
    "testCenturies": 30,
    "worldCupWins": [
      "2011"
    ],
    "iplTeams": [
      "Royal Challengers Bangalore"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "carl-hooper-52066",
    "name": "Carl Hooper",
    "aliases": [
      "hooper"
    ],
    "teams": [
      "West Indies"
    ],
    "testRuns": 5762,
    "testWickets": 114,
    "odiWickets": 193,
    "t20iWickets": 0,
    "testCenturies": 13,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": true
  },
  {
    "id": "pat-cummins",
    "name": "Pat Cummins",
    "aliases": [
      "cummins",
      "pat"
    ],
    "teams": [
      "Australia"
    ],
    "testRuns": 870,
    "testWickets": 272,
    "odiWickets": 124,
    "t20iWickets": 53,
    "testCenturies": 0,
    "worldCupWins": [
      "2023"
    ],
    "iplTeams": [
      "Kolkata Knight Riders"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "inzamam-ul-haq",
    "name": "Inzamam-ul-Haq",
    "aliases": [
      "inzamam",
      "inzi"
    ],
    "teams": [
      "Pakistan"
    ],
    "testRuns": 8830,
    "testWickets": 1,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 25,
    "worldCupWins": [
      "1992"
    ],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "ab-de-villiers-44936",
    "name": "AB de Villiers",
    "aliases": [
      "de villiers",
      "ab",
      "mr 360"
    ],
    "teams": [
      "South Africa"
    ],
    "testRuns": 8765,
    "testWickets": 1,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 22,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru",
      "Delhi Capitals"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "vvs-laxman",
    "name": "VVS Laxman",
    "aliases": [
      "laxman",
      "very very special",
      "vvs"
    ],
    "teams": [
      "India"
    ],
    "testRuns": 8781,
    "testWickets": 0,
    "odiWickets": 2,
    "t20iWickets": 0,
    "testCenturies": 17,
    "worldCupWins": [],
    "iplTeams": [
      "Deccan Chargers"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "david-warner",
    "name": "David Warner",
    "aliases": [
      "warner",
      "davey",
      "bull"
    ],
    "teams": [
      "Australia"
    ],
    "testRuns": 8695,
    "testWickets": 1,
    "odiWickets": 3,
    "t20iWickets": 2,
    "testCenturies": 26,
    "worldCupWins": [
      "2015",
      "2023"
    ],
    "iplTeams": [
      "Sunrisers Hyderabad",
      "Delhi Capitals"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "matthew-hayden",
    "name": "Matthew Hayden",
    "aliases": [
      "hayden",
      "haydos"
    ],
    "teams": [
      "Australia"
    ],
    "testRuns": 8625,
    "testWickets": 0,
    "odiWickets": 4,
    "t20iWickets": 0,
    "testCenturies": 30,
    "worldCupWins": [
      "2003",
      "2007"
    ],
    "iplTeams": [
      "Chennai Super Kings"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "kevin-pietersen",
    "name": "Kevin Pietersen",
    "aliases": [
      "pietersen",
      "kp"
    ],
    "teams": [
      "England"
    ],
    "testRuns": 8181,
    "testWickets": 10,
    "odiWickets": 7,
    "t20iWickets": 2,
    "testCenturies": 23,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bangalore",
      "Delhi Capitals"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "sourav-ganguly",
    "name": "Sourav Ganguly",
    "aliases": [
      "ganguly",
      "dada",
      "prince of calcutta"
    ],
    "teams": [
      "India"
    ],
    "testRuns": 7212,
    "testWickets": 32,
    "odiWickets": 100,
    "t20iWickets": 0,
    "testCenturies": 16,
    "worldCupWins": [],
    "iplTeams": [
      "Kolkata Knight Riders"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "clive-lloyd-52345",
    "name": "Clive Lloyd",
    "aliases": [
      "lloyd",
      "hubert"
    ],
    "teams": [
      "West Indies"
    ],
    "testRuns": 7515,
    "testWickets": 10,
    "odiWickets": 37,
    "t20iWickets": 0,
    "testCenturies": 19,
    "worldCupWins": [
      "1975",
      "1979"
    ],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "justin-langer",
    "name": "Justin Langer",
    "aliases": [
      "langer",
      "jl"
    ],
    "teams": [
      "Australia"
    ],
    "testRuns": 7696,
    "testWickets": 2,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 23,
    "worldCupWins": [
      "1999",
      "2003"
    ],
    "iplTeams": [],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "ross-taylor",
    "name": "Ross Taylor",
    "aliases": [
      "taylor",
      "ross",
      "l-tay"
    ],
    "teams": [
      "New Zealand"
    ],
    "testRuns": 7683,
    "testWickets": 1,
    "odiWickets": 15,
    "t20iWickets": 2,
    "testCenturies": 19,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "mohammad-yousuf",
    "name": "Mohammad Yousuf",
    "aliases": [
      "yousuf",
      "yousaf",
      "mohammad yousuf"
    ],
    "teams": [
      "Pakistan"
    ],
    "testRuns": 7530,
    "testWickets": 2,
    "odiWickets": 3,
    "t20iWickets": 0,
    "testCenturies": 24,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "mark-taylor",
    "name": "Mark Taylor",
    "aliases": [
      "mark taylor",
      "tubby"
    ],
    "teams": [
      "Australia"
    ],
    "testRuns": 7525,
    "testWickets": 1,
    "odiWickets": 2,
    "t20iWickets": 0,
    "testCenturies": 19,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "chris-gayle",
    "name": "Chris Gayle",
    "aliases": [
      "gayle",
      "universe boss",
      "chris"
    ],
    "teams": [
      "West Indies"
    ],
    "testRuns": 7214,
    "testWickets": 5,
    "odiWickets": 167,
    "t20iWickets": 93,
    "testCenturies": 15,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bangalore",
      "Kings XI Punjab"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "aravinda-de-silva-48462",
    "name": "Aravinda de Silva",
    "aliases": [
      "de silva",
      "aravinda"
    ],
    "teams": [
      "Sri Lanka"
    ],
    "testRuns": 6361,
    "testWickets": 29,
    "odiWickets": 106,
    "t20iWickets": 0,
    "testCenturies": 20,
    "worldCupWins": [
      "1996"
    ],
    "iplTeams": [],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "tillakaratne-dilshan",
    "name": "Tillakaratne Dilshan",
    "aliases": [
      "dilshan",
      "tillekeratne",
      "dilscoop"
    ],
    "teams": [
      "Sri Lanka"
    ],
    "testRuns": 5492,
    "testWickets": 53,
    "odiWickets": 106,
    "t20iWickets": 32,
    "testCenturies": 16,
    "worldCupWins": [],
    "iplTeams": [
      "Delhi Capitals"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "jonny-bairstow",
    "name": "Jonny Bairstow",
    "aliases": [
      "bairstow",
      "jonny"
    ],
    "teams": [
      "England"
    ],
    "testRuns": 6828,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 30,
    "worldCupWins": [
      "2019"
    ],
    "iplTeams": [
      "Sunrisers Hyderabad",
      "Punjab Kings"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "brendon-mccullum",
    "name": "Brendon McCullum",
    "aliases": [
      "mccullum",
      "baz"
    ],
    "teams": [
      "New Zealand"
    ],
    "testRuns": 6453,
    "testWickets": 4,
    "odiWickets": 11,
    "t20iWickets": 18,
    "testCenturies": 12,
    "worldCupWins": [],
    "iplTeams": [
      "Kolkata Knight Riders",
      "Chennai Super Kings"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "nasser-hussain",
    "name": "Nasser Hussain",
    "aliases": [
      "hussain",
      "nasser"
    ],
    "teams": [
      "England"
    ],
    "testRuns": 5764,
    "testWickets": 4,
    "odiWickets": 6,
    "t20iWickets": 0,
    "testCenturies": 14,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "martin-crowe",
    "name": "Martin Crowe",
    "aliases": [
      "crowe",
      "hogan"
    ],
    "teams": [
      "New Zealand"
    ],
    "testRuns": 5444,
    "testWickets": 14,
    "odiWickets": 38,
    "t20iWickets": 0,
    "testCenturies": 17,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "arjuna-ranatunga-50244",
    "name": "Arjuna Ranatunga",
    "aliases": [
      "ranatunga",
      "arjuna"
    ],
    "teams": [
      "Sri Lanka"
    ],
    "testRuns": 5105,
    "testWickets": 16,
    "odiWickets": 69,
    "t20iWickets": 0,
    "testCenturies": 4,
    "worldCupWins": [
      "1996"
    ],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "adam-gilchrist-5390",
    "name": "Adam Gilchrist",
    "aliases": [
      "gilchrist",
      "gilly"
    ],
    "teams": [
      "Australia"
    ],
    "testRuns": 5570,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 17,
    "worldCupWins": [
      "1999",
      "2003",
      "2007"
    ],
    "iplTeams": [
      "Deccan Chargers"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "ms-dhoni",
    "name": "MS Dhoni",
    "aliases": [
      "dhoni",
      "msd",
      "captain cool",
      "thala"
    ],
    "teams": [
      "India"
    ],
    "testRuns": 4876,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 6,
    "worldCupWins": [
      "2011"
    ],
    "iplTeams": [
      "Chennai Super Kings"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "rohit-sharma",
    "name": "Rohit Sharma",
    "aliases": [
      "rohit",
      "hitman",
      "ro"
    ],
    "teams": [
      "India"
    ],
    "testRuns": 4301,
    "testWickets": 0,
    "odiWickets": 8,
    "t20iWickets": 0,
    "testCenturies": 12,
    "worldCupWins": [
      "2011"
    ],
    "iplTeams": [
      "Mumbai Indians",
      "Deccan Chargers"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "babar-azam-348144",
    "name": "Babar Azam",
    "aliases": [
      "babar",
      "king babar"
    ],
    "teams": [
      "Pakistan"
    ],
    "testRuns": 4222,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 9,
    "worldCupWins": [
      "2019"
    ],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "faf-du-plessis-44828",
    "name": "Faf du Plessis",
    "aliases": [
      "faf",
      "du plessis"
    ],
    "teams": [
      "South Africa"
    ],
    "testRuns": 4163,
    "testWickets": 0,
    "odiWickets": 1,
    "t20iWickets": 0,
    "testCenturies": 13,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru",
      "Chennai Super Kings"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "lasith-malinga",
    "name": "Lasith Malinga",
    "aliases": [
      "malinga",
      "slinga malinga"
    ],
    "teams": [
      "Sri Lanka"
    ],
    "testRuns": 673,
    "testWickets": 101,
    "odiWickets": 338,
    "t20iWickets": 107,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Mumbai Indians"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "shahid-afridi",
    "name": "Shahid Afridi",
    "aliases": [
      "afridi",
      "boom boom",
      "lala"
    ],
    "teams": [
      "Pakistan"
    ],
    "testRuns": 1716,
    "testWickets": 48,
    "odiWickets": 395,
    "t20iWickets": 98,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [],
    "captainedNational": true,
    "isAllrounder": true
  },
  {
    "id": "shoaib-malik-42657",
    "name": "Shoaib Malik",
    "aliases": [
      "shoaib malik",
      "malik"
    ],
    "teams": [
      "Pakistan"
    ],
    "testRuns": 1898,
    "testWickets": 32,
    "odiWickets": 158,
    "t20iWickets": 62,
    "testCenturies": 1,
    "worldCupWins": [],
    "iplTeams": [
      "Delhi Capitals"
    ],
    "captainedNational": true,
    "isAllrounder": true
  },
  {
    "id": "jos-buttler",
    "name": "Jos Buttler",
    "aliases": [
      "buttler",
      "jos"
    ],
    "teams": [
      "England"
    ],
    "testRuns": 2727,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 5,
    "worldCupWins": [
      "2019"
    ],
    "iplTeams": [
      "Mumbai Indians",
      "Rajasthan Royals"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "yuvraj-singh",
    "name": "Yuvraj Singh",
    "aliases": [
      "yuvraj",
      "yuvi",
      "six sixes"
    ],
    "teams": [
      "India"
    ],
    "testRuns": 1900,
    "testWickets": 9,
    "odiWickets": 111,
    "t20iWickets": 28,
    "testCenturies": 3,
    "worldCupWins": [
      "2011"
    ],
    "iplTeams": [
      "Kings XI Punjab",
      "Royal Challengers Bangalore",
      "Sunrisers Hyderabad"
    ],
    "captainedNational": false,
    "isAllrounder": true
  },
  {
    "id": "eoin-morgan-24598",
    "name": "Eoin Morgan",
    "aliases": [
      "morgan",
      "morgs"
    ],
    "teams": [
      "England"
    ],
    "testRuns": 1326,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 1,
    "worldCupWins": [
      "2019"
    ],
    "iplTeams": [
      "Kolkata Knight Riders",
      "Royal Challengers Bengaluru",
      "Sunrisers Hyderabad"
    ],
    "captainedNational": true,
    "isAllrounder": false
  },
  {
    "id": "hardik-pandya",
    "name": "Hardik Pandya",
    "aliases": [
      "hardik",
      "pandya"
    ],
    "teams": [
      "India"
    ],
    "testRuns": 532,
    "testWickets": 17,
    "odiWickets": 77,
    "t20iWickets": 53,
    "testCenturies": 1,
    "worldCupWins": [],
    "iplTeams": [
      "Mumbai Indians",
      "Gujarat Titans"
    ],
    "captainedNational": true,
    "isAllrounder": true
  },
  {
    "id": "glenn-maxwell",
    "name": "Glenn Maxwell",
    "aliases": [
      "maxwell",
      "maxi",
      "big show"
    ],
    "teams": [
      "Australia"
    ],
    "testRuns": 682,
    "testWickets": 7,
    "odiWickets": 54,
    "t20iWickets": 44,
    "testCenturies": 1,
    "worldCupWins": [
      "2023"
    ],
    "iplTeams": [
      "Kings XI Punjab",
      "Delhi Capitals",
      "Royal Challengers Bangalore"
    ],
    "captainedNational": false,
    "isAllrounder": true
  },
  {
    "id": "owais-shah-20123",
    "name": "Owais Shah",
    "aliases": [],
    "teams": [
      "England"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Delhi Capitals",
      "Kolkata Knight Riders"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "cameron-white-8291",
    "name": "Cameron White",
    "aliases": [],
    "teams": [
      "Australia"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru",
      "Sunrisers Hyderabad"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "andrew-mcdonald-6553",
    "name": "Andrew McDonald",
    "aliases": [],
    "teams": [
      "Australia"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru",
      "Delhi Capitals"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "josh-hazlewood-288284",
    "name": "Josh Hazlewood",
    "aliases": [],
    "teams": [
      "Australia"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Mumbai Indians"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "dirk-nannes-6981",
    "name": "Dirk Nannes",
    "aliases": [],
    "teams": [
      "New Zealand"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru",
      "Delhi Capitals"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "ben-rohrer-7547",
    "name": "Ben Rohrer",
    "aliases": [],
    "teams": [
      "Australia"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Delhi Capitals"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "dominic-thornely-8002",
    "name": "Dominic Thornely",
    "aliases": [],
    "teams": [
      "Australia"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Mumbai Indians"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "chris-morris-439952",
    "name": "Chris Morris",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Delhi Capitals",
      "Chennai Super Kings"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "herschelle-gibbs-45224",
    "name": "Herschelle Gibbs",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Mumbai Indians"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "wayne-parnell-265564",
    "name": "Wayne Parnell",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Delhi Capitals"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "robin-peterson-46750",
    "name": "Robin Peterson",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Mumbai Indians"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "morn-morkel-46538",
    "name": "Morné Morkel",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Kolkata Knight Riders",
      "Delhi Capitals"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "charl-langeveldt-45963",
    "name": "Charl Langeveldt",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Kolkata Knight Riders"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "davy-jacobs-45782",
    "name": "Davy Jacobs",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Mumbai Indians"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "ryan-mclaren-46393",
    "name": "Ryan McLaren",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Kolkata Knight Riders",
      "Mumbai Indians"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "albie-morkel-46248",
    "name": "Albie Morkel",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru",
      "Delhi Capitals",
      "Chennai Super Kings"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "andr-nel-46569",
    "name": "André Nel",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Mumbai Indians"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "david-wiese-221140",
    "name": "David Wiese",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "dillon-du-preez-44938",
    "name": "Dillon du Preez",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "johan-botha-44149",
    "name": "Johan Botha",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Delhi Capitals"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "colin-ingram-45705",
    "name": "Colin Ingram",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Delhi Capitals"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "morn-van-wyk-47711",
    "name": "Morné van Wyk",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Kolkata Knight Riders"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "jp-duminy-44932",
    "name": "JP Duminy",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Mumbai Indians",
      "Delhi Capitals",
      "Sunrisers Hyderabad"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "marchant-de-lange-393279",
    "name": "Marchant de Lange",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Kolkata Knight Riders",
      "Mumbai Indians"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "justin-kemp-45797",
    "name": "Justin Kemp",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Chennai Super Kings"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "kyle-abbott-297583",
    "name": "Kyle Abbott",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Chennai Super Kings"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "mark-boucher-44111",
    "name": "Mark Boucher",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru",
      "Kolkata Knight Riders"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "johan-van-der-wath-47693",
    "name": "Johan van der Wath",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "quinton-de-kock-379143",
    "name": "Quinton de Kock",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Delhi Capitals",
      "Royal Challengers Bengaluru",
      "Sunrisers Hyderabad",
      "Mumbai Indians"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "gulam-bodi-44089",
    "name": "Gulam Bodi",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Delhi Capitals"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "kevin-pietersen-19296",
    "name": "Kevin Pietersen",
    "aliases": [],
    "teams": [
      "South Africa"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Delhi Capitals",
      "Royal Challengers Bengaluru"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "dwayne-smith-53118",
    "name": "Dwayne Smith",
    "aliases": [],
    "teams": [
      "West Indies"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Mumbai Indians"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "javon-searles-230554",
    "name": "Javon Searles",
    "aliases": [],
    "teams": [
      "West Indies"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Kolkata Knight Riders"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "jason-holder-391485",
    "name": "Jason Holder",
    "aliases": [],
    "teams": [
      "West Indies"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Kolkata Knight Riders",
      "Chennai Super Kings",
      "Sunrisers Hyderabad"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "romario-shepherd-677077",
    "name": "Romario Shepherd",
    "aliases": [],
    "teams": [
      "West Indies"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Sunrisers Hyderabad"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "christopher-barnwell-330408",
    "name": "Christopher Barnwell",
    "aliases": [],
    "teams": [
      "West Indies"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "rovman-powell-820351",
    "name": "Rovman Powell",
    "aliases": [],
    "teams": [
      "West Indies"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Kolkata Knight Riders"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "jacob-oram-38062",
    "name": "Jacob Oram",
    "aliases": [],
    "teams": [
      "New Zealand"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Mumbai Indians",
      "Chennai Super Kings"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "brett-lee-6278",
    "name": "Brett Lee",
    "aliases": [],
    "teams": [
      "New Zealand"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Kolkata Knight Riders"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "muttiah-muralitharan-49636",
    "name": "Muttiah Muralitharan",
    "aliases": [],
    "teams": [
      "New Zealand"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru",
      "Chennai Super Kings"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "aiden-blizzard-4498",
    "name": "Aiden Blizzard",
    "aliases": [],
    "teams": [
      "New Zealand"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Mumbai Indians"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "sourav-sarkar-34402",
    "name": "Sourav Sarkar",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Kolkata Knight Riders"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "gaurav-dhiman-28619",
    "name": "Gaurav Dhiman",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "ashish-nehra-31820",
    "name": "Ashish Nehra",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Mumbai Indians",
      "Delhi Capitals",
      "Sunrisers Hyderabad",
      "Chennai Super Kings"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "ashok-dinda-227712",
    "name": "Ashok Dinda",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Kolkata Knight Riders",
      "Royal Challengers Bengaluru",
      "Delhi Capitals"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "mahendra-singh-dhoni-28081",
    "name": "Mahendra Singh Dhoni",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [
      "2011"
    ],
    "iplTeams": [
      "Chennai Super Kings"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "k-vasudevadas-35724",
    "name": "K. Vasudevadas",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Chennai Super Kings"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "yalaka-venugopal-rao-35805",
    "name": "Yalaka Venugopal Rao",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Delhi Capitals",
      "Sunrisers Hyderabad"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "vinit-indulkar-29537",
    "name": "Vinit Indulkar",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Kolkata Knight Riders"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "cheteshwar-pujara-32540",
    "name": "Cheteshwar Pujara",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Kolkata Knight Riders",
      "Royal Challengers Bengaluru"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "rajat-bhatia-26907",
    "name": "Rajat Bhatia",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Delhi Capitals",
      "Kolkata Knight Riders"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "bipul-sharma-35928",
    "name": "Bipul Sharma",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Sunrisers Hyderabad"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "swapnil-singh-232292",
    "name": "Swapnil Singh",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Mumbai Indians",
      "Royal Challengers Bengaluru"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "shashi-ranjan-33097",
    "name": "Shashi Ranjan",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Delhi Capitals"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "sanjay-bangar-27225",
    "name": "Sanjay Bangar",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Kolkata Knight Riders"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "tajinder-singh-1079860",
    "name": "Tajinder Singh",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Mumbai Indians"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "shahbaz-nadeem-31872",
    "name": "Shahbaz Nadeem",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Delhi Capitals"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "zaheer-khan-30102",
    "name": "Zaheer Khan",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Mumbai Indians",
      "Royal Challengers Bengaluru",
      "Delhi Capitals"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "syed-mohammed-35261",
    "name": "Syed Mohammed",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "tanmay-mishra-24790",
    "name": "Tanmay Mishra",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "rohan-raje-290713",
    "name": "Rohan Raje",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Mumbai Indians"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "munaf-patel-32965",
    "name": "Munaf Patel",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Mumbai Indians"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "naman-ojha-32102",
    "name": "Naman Ojha",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Delhi Capitals",
      "Sunrisers Hyderabad"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "j-arunkumar-26291",
    "name": "J. Arunkumar",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "natraj-behera-291438",
    "name": "Natraj Behera",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Kolkata Knight Riders"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "wasim-jaffer-29646",
    "name": "Wasim Jaffer",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "mohammad-kaif-29990",
    "name": "Mohammad Kaif",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "vijay-shankar-477021",
    "name": "Vijay Shankar",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Delhi Capitals",
      "Sunrisers Hyderabad",
      "Chennai Super Kings"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "tejashwi-yadav-344286",
    "name": "Tejashwi Yadav",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Delhi Capitals"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "piyush-chawla-32966",
    "name": "Piyush Chawla",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Kolkata Knight Riders"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "devraj-patil-32389",
    "name": "Devraj Patil",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "robin-uthappa-35582",
    "name": "Robin Uthappa",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Kolkata Knight Riders",
      "Mumbai Indians",
      "Royal Challengers Bengaluru"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "mohammed-siraj-940973",
    "name": "Mohammed Siraj",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru",
      "Sunrisers Hyderabad"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "varun-aaron-360911",
    "name": "Varun Aaron",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Kolkata Knight Riders",
      "Delhi Capitals"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "balachandra-akhil-26206",
    "name": "Balachandra Akhil",
    "aliases": [],
    "teams": [
      "India"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Royal Challengers Bengaluru"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "suraj-randiv-50438",
    "name": "Suraj Randiv",
    "aliases": [],
    "teams": [
      "Sri Lanka"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Chennai Super Kings"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "thilan-thushara-49677",
    "name": "Thilan Thushara",
    "aliases": [],
    "teams": [
      "Sri Lanka"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Chennai Super Kings"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "chamara-kapugedera-209457",
    "name": "Chamara Kapugedera",
    "aliases": [],
    "teams": [
      "Sri Lanka"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Chennai Super Kings"
    ],
    "captainedNational": false,
    "isAllrounder": false
  },
  {
    "id": "thisara-perera-233514",
    "name": "Thisara Perera",
    "aliases": [],
    "teams": [
      "Sri Lanka"
    ],
    "testRuns": 0,
    "testWickets": 0,
    "odiWickets": 0,
    "t20iWickets": 0,
    "testCenturies": 0,
    "worldCupWins": [],
    "iplTeams": [
      "Mumbai Indians",
      "Chennai Super Kings"
    ],
    "captainedNational": false,
    "isAllrounder": false
  }
];